name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-15"

kv_namespaces = [
    # 注意：将下面的 id 替换为你自己拷贝的 KV 命名空间 id 才能正常使用！
    { binding = "SHORT_URLS", id = "9edc3d9387724fbfbc20407080128691" },
]

[env.dev]
kv_namespaces = [
    { binding = "SHORT_URLS", id = "9edc3d9387724fbfbc20407080128691" },
]

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[triggers]
crons = ["0 2 */1 * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true
